# YAML linting configuration
# https://yamllint.readthedocs.io

extends: default

rules:
  # Line length: Allow 120 chars (common in CI/CD files)
  line-length:
    max: 120
    level: warning

  # Allow yes/no/on/off as booleans
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Indentation: 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments: Allow one space after #
  comments:
    min-spaces-from-content: 1

  # Document start: Not required
  document-start: disable

  # Empty values: Allow
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Key ordering: Not enforced
  key-ordering: disable

  # Trailing spaces: Forbid
  trailing-spaces: enable

  # New line at end of file
  new-line-at-end-of-file: enable
